apiVersion: config.loki.grafana.com/v1
kind: ProjectConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8080
  secure: false
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: loki-operator.grafana.com
featureGates:
  #
  # Component feature gates
  #
  lokiStackGateway: true
  restrictedPodSecurityStandard: false
  #
  # Webhook feature gates
  #
  lokiStackWebhook: true
  alertingRuleWebhook: true
  recordingRuleWebhook: true
